name: check
run-name: check
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Adding markdown
        run: | 
          echo '### continue' >> $GITHUB_STEP_SUMMARY
          echo '[ ] completed' >> $GITHUB_STEP_SUMMARY

      - name: Adding markdown
        run: | 
          curl -o test.xml https://github.com/testmoapp/junitxml/blob/main/examples/junit-complete.xml

      - name: Check for check
        uses: actions/github-script@v7
        timeout-minutes: 5
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addCodeBlock('console.log(\'hello world\')', "js")
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass ✅'],
                ['bar.js', 'Fail ❌'],
                ['test.js', 'Pass ✅']
              ])
              .addLink('View staging deployment!', 'https://github.com')
              .write()

      - name: Publish Unit Tests
        if: success() || failure()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: Core Tests
          path: 'test.xml'
          reporter: jest-junit
          list-tests: failed
          fail-on-error: false 
