name: check
run-name: check
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Adding markdown
        run: | 
          echo '### continue' >> $GITHUB_STEP_SUMMARY
          echo '[ ] completed' >> $GITHUB_STEP_SUMMARY

      - name: Check for check
        uses: actions/github-script@v7
        timeout-minutes: 5
        with:
          script: |
            while (true) {
              if (core.summary.stringify().indexOf("[x]") != -1) {
                return "passed";
              }
            }
