name: Jobs ${{ github.event.pull_request.number || github.ref }}

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        run: |
          for i in 1 2 3 4 5
          do
            echo "Mendax Current number is: $i"
          done
  test3:
      needs: test2
      runs-on: ubuntu-latest
      steps:
        - name: Set Environment Failed
          run: |
            for i in 1 2 3 4 5
            do
              echo "Mendax Current number is: $i"
            done
  test2:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        run: |
          for i in 1 2 3 4 5
          do
            echo "Mendax Current number is: $i"
          done
  
