name: Test multiple jobs

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            while (true) {
              core.debug("Running something at the moment");
              console.log("test")
            }
            core.setFailed(`Deployment Failed ${ process.env.GITHUB_REF_NAME }\n)
  
