---
name: dispatch
run-name: ${{ inputs.test }} dispatch
on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: choice
        options:
          - test
          - other
        default: test

jobs:
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment Failed')

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        if: inputs.test == 'test' && !startsWith(github.ref, format('refs/tags/v', '{0}'))
        with:
          script: |
            core.setFailed(`Deployment Failed ${ process.env.GITHUB_REF_NAME }` + process.env.INPUTS.TEST)

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        if: inputs.test == 'test' && !startsWith(github.ref, format('refs/tags/v', '{0}'))
        run: |
            echo "test"
            echo ${{ github.ref }}
            echo ${{ inputs.app }}
            exit 1
