---
name: dispatch
run-name: ${{ inputs.test }} dispatch
on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: choice
        options:
          - test
          - other
        default: test

jobs:
  job1:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment Failed')

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        if: inputs.test == 'test'
        run: |
          if ${{ !startsWith(github.ref, format('refs/tags/v{0}@', "") }}; then
            echo "test"
            echo ${{ github.ref }}
            echo ${{ inputs.app }}
            exit 1
          fi
