---
name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: choice
        options:
          - test
        default: test

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment Failed')

  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    if: ${{ always() && (needs.job1.result == 'failure') }}
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Deployment Failed')
