---
name: Pr Label

on:
  pull_request:
    types: labeled

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Semantic Release PR Title Check
        uses: osl-incubator/semantic-release-pr-title-check@v1.4.3
        
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            return "Hello! world"
