---
name: Pr Label

on:
  pull_request:
    types: labeled

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Failed
        uses: actions/github-script@v7
        with:
          script: |
            return "Hello!"
