name: Release
run-name: release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Adding markdown
        run: echo '### Test 🚀' >> $GITHUB_STEP_SUMMARY

      - uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Final markdown
        run: echo '## ${{ steps.tag.outputs.new_tag }}' >> $GITHUB_STEP_SUMMARY
          
