on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_release_rules: test,minor
          tag_prefix: pre
          
