on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mathieudutour/github-tag-action@v6.1
        with:
          tag_prefix: pre
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
