name: Release
run-name: release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Adding markdown
        run: echo '### Test 🚀' >> $GITHUB_STEP_SUMMARY

      - uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release
          body: ${{ steps.tag.outputs.changelog }}

      - name: Final markdown
        run: echo '# ${{ steps.tag.outputs.new_tag }}' >> $GITHUB_STEP_SUMMARY
          
