name: Services
on:
  push:
    tags-ignore:
      - '**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v6.1.0
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"

  # localstack:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       test: []
  #   services:
  #     localstack:
  #       image: localstack/localstack:latest
  #       env:
  #         SERVICES: ec2, s3
  #         DEFAULT_REGION: us-east-1
  #         AWS_ACCESS_KEY_ID: test
  #         AWS_SECRET_ACCESS_KEY: test
  #       ports:
  #         - 4566:4566
  #         - 4571:4571
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10' 
      
  #     - name: awslocal cli
  #       run: pip install awscli-local

  #     - name: awslocal create bucket
  #       run: awslocal s3api create-bucket --bucket sample-bucket

  #     - name: awslocal list bucket
  #       run: awslocal s3api list-buckets
