name: Services
on:
  push:

jobs:
  localstack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [test1, test2, test3, test4]
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: ec2, s3
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566
          - 4571:4571
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: awslocal cli
        run: pip install awscli-local

      - name: awslocal create bucket
        run: awslocal s3api create-bucket --bucket sample-bucket

      - name: awslocal list bucket
        run: awslocal s3api list-buckets
